### ISSUE TITLE
 🏆Looking for new trophy types

### ISSUE THREAD

**Issue by ryo-ma** [ryo-ma/github-profile-trophy#10]
If you have any ideas please let us know.
The target of aggregation is preferable to be able to obtain it using GitHub API.

**Comment by ryo-ma** [comment]
Gradually, I want to add new secret trophies, so I'll consider them.

**Comment by ryo-ma** [comment]
Memo: 
* All S rank over
* Event trophy: A repository of Christmas name created at 2020 December 25. etc..

**Comment by VegaDeftwing** [comment]
Would it be possible to integrate with something to show previous interaction with / completion of Hacktoberfest? The 'cheat' way to do it would just to confirm weather not 4 PRs were done during October of any given year rather than checking with something potentially interacting with a 3rd party api

**Comment by ryo-ma** [comment]
@VegaDeftwing Good idea.
I will consider the method

**Comment by Pralhad-Nasane** [comment]
@ryo-ma Hey i have a small request if it possible then please add this tokyonight theme in your repo
` tokyonight: {
    title_color: "70a5fd",
    icon_color: "bf91f3",
    text_color: "38bdae",
    bg_color: "1a1b27",
}
`

**Comment by qoomon** [comment]
* Look at stars of all repositories (amount)
* Look at contributors of all repositories (amount)
* Look at forks of all repositories (amount)

**Comment by subnut** [comment]
### Look at number of repositories contributed to
Similar to https://github.com/anuraghazra/github-readme-stats

**Comment by subnut** [comment]
Ping @ryo-ma

**Comment by qoomon** [comment]
Is this project still alive?

**Comment by ryo-ma** [comment]
@qoomon 
I am suspending about adding normal trophies. But I want to add secret trophies.

Like this.
https://github.com/ryo-ma/github-profile-trophy/issues/10#issuecomment-690842129

**Comment by Koushikphy** [comment]
how do you get that multilanguage trophy, I saw it on your @ryo-ma page, but it doesn't show on mine?

**Comment by ryo-ma** [comment]
@Koushikphy 
How to get the trophy is a secret. Because it is a secret rank.
But hints are here.
https://github.com/ryo-ma/github-profile-trophy/blob/master/src/github_api_client.ts#L86

**Comment by Koushikphy** [comment]
Ok, I get it. The multilanguage trophy has a minimum requirement of 10 languages (https://github.com/ryo-ma/github-profile-trophy/blob/master/src/trophies.ts#L106). But mine is 6.

**Comment by RayhanADev** [comment]
Heya @ryo-ma ! I don't know if this is still active xD
### Maybe add a secret trophy for `x` amount of badges/shields used?

This might encourage people to use badges more often ƪ(˘⌣˘)ʃ. A possible sort of cheaty implementation could be to scan for the amount of popular shield/badge sites on README files?

Let me know what you think!

**Comment by Nirzak** [comment]
A section for number of code reviews can be added!

**Comment by Time-dragon** [comment]
Discussions _answered_ because I asked for a discussions *made* trophy.

**Comment by HoLLy-HaCKeR** [comment]
With github sponsors being a thing now, you could add a trophy depending on the amount of money you donate each month.

**Comment by ura43** [comment]
> With github sponsors being a thing now, you could add a trophy depending on the amount of money you donate each month.

I agree but would say this should be a secret trophy. The trophies are supposed to measure activity after all and I dislike the idea of a highly productive college student having C rank on donations because he can't afford dropping more than a few bucks a month

**Comment by aeristhy** [comment]
> I agree but would say this should be a secret trophy. The trophies are supposed to measure activity after all and I dislike the idea of a highly productive college student having C rank on donations because he can't afford dropping more than a few bucks a month

As a poor college student, I completely agree

**Comment by ura43** [comment]
How about a code review trophy?

**Comment by EmmanuelMess** [comment]
Organization collaboration:
* At least a commit a month
* For X years
in any main branch of an organization

**Comment by ura43** [comment]
Make a code review trophy please

**Comment by slyg3nius** [comment]
Make a programming languages ranking as trophy.

**Comment by myConsciousness** [comment]
Is requests through this issue still valid?

**Comment by lucasrmagalhaes** [comment]
Secret Trophies is very cool!

**Comment by MitkoVtori** [comment]
Trophy for most stars on "ONE" repository

**Comment by 3kh0** [comment]
Code review?

**Comment by george-gca** [comment]
What kind of information can you get through the GitHub API?

Is it possible to see, for example, how many GitHub Project sites one user has? Or how many repos one user have with Wiki or CI configured? Maybe even handle this as a percentage, for example, the percentage of the repos of the user  that have a `.gitignore` file in it, so it is using some good practices.

**Comment by port19x** [comment]
I disagree with your best practices take @george-gca 
Much more valuable are the artifacts listed under `Insights>Community Standards` such as code of conduct, security policy, issue templates and pr templates.
Not all repos need a `.gitignore` and the use of `tags` depends on the release model

**Comment by port19x** [comment]
Perhaps a trophy could be created for number of repos that have all of the community standards artifacts

**Comment by george-gca** [comment]
Sure, these were all suggestions. Also I said tags there, but actually I was thinking about `topics`.

**Comment by holly-hacker** [comment]
I'm a fan of a trophy scaled to the amount of stars in your most popular repo, but I feel like GitHub's community standards or some "best practices" are too arbitrary. There are repos that don't need these (take the linux kernel for example) so it feels weird to make trophies for something that not everybody needs.

**Comment by george-gca** [comment]
That's why I think this kind of trophy would be useful as a number, not a percentage. For example, a trophy with the number of repos that follow GitHub community standards is ok, but one based on the percentage of your repos that follow them is not.

**Comment by Dzhake** [comment]
Uses his own fork of this repo (so you get this trophy if link is not https://github-profile-trophy.vercel.app)
How many times his repos were forked (not really secret trophy 🤔 )
(i have no ideas..)

**Comment by port19x** [comment]
![image](https://github.com/ryo-ma/github-profile-trophy/assets/82055622/8fda7ea7-217c-4805-b670-8a3259f5c035)

**Comment by george-gca** [comment]
One trophy that would be interesting is the number of accepted answers in Q&As discussions.

**Comment by port19x** [comment]
That is literally one of the official github profile achievements

**Comment by george-gca** [comment]
As it is some other trophies, like PRs and stars. The difference would be that accepted answers stops at 32, while the trophy could go beyond that.

**Comment by OS-Scratch** [comment]
You could add a streak trophy?

**Comment by jeanpmodev** [comment]
Bringing authenticity is the way to go.

Trophy could be a certification company.

I wouldn't increase the range of criteria and metrics.

I would increase the veracity of the trophies.
