### ISSUE TITLE
Requst: Support stars for organization-created repositories

### ISSUE THREAD

**Issue by byronbytes** [ryo-ma/github-profile-trophy#106]
I have a project under an organization which has a lot of stars, but it doesn't show up on my profile unfortunately for stars. Is there a way to add a fix for this?

thank you!
- byron

**Comment by kirankotari** [comment]
@byronbytes I have a same issue. @ryo-ma do you have time to look into it?

**Comment by DogeLord081** [comment]
Still an issue for me, anyone have any time to look into it?
