### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Camroku** [ryo-ma/github-profile-trophy#109]
It gives this error:
![Screenshot_20211228_222052](https://user-images.githubusercontent.com/79412062/147599868-c1b477d8-6e3a-46af-a0b7-0c08ca88fdaf.png)

**Comment by aeristhy** [comment]
Check the username properly, there must be a typo in the username field or the user does not exist.

**Comment by Camroku** [comment]
Oh, you're right. There's not a typo in the username field but in the link. This is the link I tried to use: https://github-profile-trophy-iota.vercel.app/?username=Camroku
I don't know why did I add `-iota` there.
