### ISSUE TITLE
Change rank system from C B A AA AAA S SS SSS to F E D C B A S SS

### ISSUE THREAD

**Issue by EmmanuelMess** [ryo-ma/github-profile-trophy#111]
Change rank system from C B A AA AAA S SS SSS to F E D C B A S SS. The rationale is purely to make it more readable, as more people would understand the US grading system, than the current implementation. This is similar to OSU!'s rating system.

**Comment by sunsided** [comment]
Heya, I want to share some thoughts on this. Personally, I'm not a fan of this for various reasons, but one argument to be made here is that while the US have the highest (active) user count for any given country according to [this 2018 analysis](https://www.benfrederickson.com/github-developer-locations/), the number of non-US users is significantly higher. 

Looking just at the values given there, the US on rank 1 has ~651k active users (out of all 2 million that have a country specified), while China on rank 2 has just ~183k. However, if you consider just the top-ten countries, all remaining nine countries together already sum up to ~871k — my point being that the OSU ranking might not make sense to the majority of users.

That being said, the current ranking also is a bit awkward, but the the "triple-A" rating at least makes pop cultural sense to me (a non-US citizen).
