### ISSUE TITLE
Forks Trophy

### ISSUE THREAD

**Issue by MrBlueBird2** [ryo-ma/github-profile-trophy#120]
I think it should also have a fork trophy, which tells that how many peoples have fork your repos, I didn't meant that if 1 person has forked 3 of your repo just show 1, show 3 instead of 1

**Comment by UjjwalSaini07** [comment]
yes i also think same

**Comment by lucasrmagalhaes** [comment]
I agree

**Comment by AryanP45** [comment]
ACK

**Comment by Ayushkhodankar** [comment]
i agree
