### ISSUE TITLE
Get Data as Image

### ISSUE THREAD

**Issue by omegaui** [ryo-ma/github-profile-trophy#129]
Hi! @ryo-ma 

I wanted to know is there any way to get the svg or any other image format from a requested url.
like
`https://github-profile-trophy.vercel.app/?${jsonData['username']}=ryo-ma&theme=${jsonData['github-profile-trophies-theme']}`

I am currently practicing flutter and preparing a `gitcard` app,
where I require the trophy data about a user.

![Screenshot 2022-03-21 221523](https://user-images.githubusercontent.com/73544069/159312280-65bc86a1-53e4-4eec-87d2-57874f2fea5d.png)

**Comment by ryo-ma** [comment]
Probably this.

```
https://github-profile-trophy.vercel.app/?username=${jsonData['username']}&theme=${jsonData['github-profile-trophies-theme']}
```
