### ISSUE TITLE
Typo in the code for theme gitdimmed

### ISSUE THREAD

**Issue by menonkartikeya** [ryo-ma/github-profile-trophy#134]
[At this point](https://github.com/ryo-ma/github-profile-trophy#gitdimmed) :

To set the theme to "**gitdimmed**":
`https://github-profile-trophy.vercel.app/?username=ryo-ma&theme=gitdimme`
The 'd' is missing in the end, it will be :
`https://github-profile-trophy.vercel.app/?username=ryo-ma&theme=gitdimmed`

**Comment by ryo-ma** [comment]
I have fixed it.
