### ISSUE TITLE
re-post to echojs

### ISSUE THREAD

**Issue by tracker1** [ryo-ma/github-profile-trophy#14]
Sorry... cleaning out spam, and accidentally deleted your post.  Feel free to repost.

**Comment by ryo-ma** [comment]
You might make a mistake.

**Comment by ryo-ma** [comment]
II forgot that I posted to echojs.
I will re-post.

**Comment by tracker1** [comment]
Yeah... there's a *LOT* of spam posts, and I deal with them one at a time.
