### ISSUE TITLE
Serverless function has crashed

### ISSUE THREAD

**Issue by adi-g15** [ryo-ma/github-profile-trophy#141]
## Issue
Currently the serverless function has crashed, and is returning 500. Code: `FUNCTION_INVOCATION_FAILED`.

### Screenshots

![image](https://user-images.githubusercontent.com/37269665/172896914-ed94b44a-578d-42ad-880f-6176fd3d5880.png)

### Example

Example URL: https://github-profile-trophy.vercel.app/?username=ryo-ma

**Comment by spenserblack** [comment]
Just tried the URL. Looks like it's working now.

**Comment by adi-g15** [comment]
> Just tried the URL. Looks like it's working now.

Oh, thanks, guess I should close this issue then :+1:

**Comment by Rongronggg9** [comment]
Now it's OK... Pretty weird. 🤔
