### ISSUE TITLE
Why is JoinedTrophy just for 2020

### ISSUE THREAD

**Issue by myConsciousness** [ryo-ma/github-profile-trophy#143]
I just wonder why is JoinedTrophy just for 2020.

**Comment by hack-parthsharma** [comment]
This is totally depends on the author buddy !

**Comment by ImaniAN** [comment]
How does it totaly depend on the Author ? Can JoinedTrophy be displayed even if you joined GitHub before 2020 ?

**Comment by AlexcastroDev** [comment]
> Can JoinedTrophy be displayed

It could be a good implementation, by having the year JoinedTrophy :D

I was reviewing the https://github.com/ryo-ma/github-profile-trophy/pull/201 of @bhavberi, and thinking if we could remove the 2020 or current year Trophy and create a new one of when someone joined.

I will put a label for "help wanted" and also put it backlog.

**Comment by ryo-ma** [comment]
The reason is that this product was launched in 2020.
