### ISSUE TITLE
Wanted to Know the Values of Threshold to Change Levels 

### ISSUE THREAD

**Issue by ChintzRuparel** [ryo-ma/github-profile-trophy#149]
Hey there, 

Amazing work on the repository.  Am a personal user of your stats reader. 

Just wanted to know the levels at which levels change and whether it is changeable when replicating it locally. 

Thanks, 
Chintz Ruparel

**Comment by Xisurthros** [comment]
I was curious as well. Quickly searching through the code I was able to find this in /src/trophy.ts 

Commits
RANK.SSS=God Committer=4000
RANK.SS=Deep Committer=2000
RANK.S=Super Committer=1000
RANK.AAA=Ultra Committer=500
RANK.AA=Hyper Committer=200
RANK.A=High Committer=100
RANK.B=Middle Committer=10
RANK.C=First Commit=1

Stars
RANK.SSS=Super Stargazer=2000
RANK.SS=High Stargazer=700
RANK.S=Stargazer=200
RANK.AAA=Super Star=100
RANK.AA=High Star=50
RANK.A=You are a Star=30
RANK.B=Middle Star=10
RANK.C=First Star=1

Followers
RANK.SSS=Super Celebrity=1000
RANK.SS=Ultra Celebrity=400
RANK.S=Hyper Celebrity=200
RANK.AAA=Famous User=100
RANK.AA=Active User=50
RANK.A=Dynamic User=20
RANK.B=Many Friends=10
RANK.C=First Friend=1

Issues
RANK.SSS=God Issuer=1000
RANK.SS=Deep Issuer=500
RANK.S=Super Issuer=200
RANK.AAA=Ultra Issuer=100
RANK.AA=Hyper Issuer=50
RANK.A=High Issuer=20
RANK.B=Middle Issuer=10
RANK.C=First Issue=1

Pull Requests
RANK.SSS=God Puller=1000
RANK.SS=Deep Puller=500
RANK.S=Super Puller=200
RANK.AAA=Ultra Puller=100
RANK.AA=Hyper Puller=50
RANK.A=High Puller=20
RANK.B=Middle Puller=10
RANK.C=First Pull=1

Repository
RANK.SSS=God Repo Creator=100
RANK.SS=Deep Repo Creator=90
RANK.S=Super Repo Creator=80
RANK.AAA=Ultra Repo Creator=50
RANK.AA=Hyper Repo Creator=30
RANK.A=High Repo Creator=20
RANK.B=Middle Repo Creator=10
RANK.C=First Repository=1

**Comment by Xisurthros** [comment]
I was curious as well. Searching through /src/trophy.ts I managed to find this.

Total Commits
RANK.SSS = "God Committer" = 4000
RANK.SS = "Deep Committer" = 2000
RANK.S = "Super Committer" = 1000
RANK.AAA = "Ultra Committer" = 500
RANK.AA = "Hyper Committer" = 200
RANK.A = "High Committer" = 100
RANK.B = "Middle Committer" = 10
RANK.C = "First Commit" = 1

Total Stars
RANK.SSS = "Super Stargazer" = 2000
RANK.SS = "High Stargazer" = 700
RANK.S = "Stargazer" = 200
RANK.AAA = "Super Star" = 100
RANK.AA = "High Star" = 50
RANK.A = "You are a Star" = 30
RANK.B = "Middle Star" = 10
RANK.C = "First Star" = 1

Total Followers
RANK.SSS = "Super Celebrity" = 1000
RANK.SS = "Ultra Celebrity" = 400
RANK.S = "Hyper Celebrity" = 200
RANK.AAA = "Famous User" = 100
RANK.AA = "Active User" = 50
RANK.A = "Dynamic User" = 20
RANK.B = "Many Friends" = 10
RANK.C = "First Friend" = 1

Total Issues
RANK.SSS = "God Issuer" = 1000
RANK.SS = "Deep Issuer" = 500
RANK.S = "Super Issuer" = 200
RANK.AAA = "Ultra Issuer" = 100
RANK.AA = "Hyper Issuer" = 50
RANK.A = "High Issuer" = 20
RANK.B = "Middle Issuer" = 10
RANK.C = "First Issue" = 1

Total Pull Requests
RANK.SSS = "God Puller" = 1000
RANK.SS = "Deep Puller" = 500
RANK.S = "Super Puller" = 200
RANK.AAA = "Ultra Puller" = 100
RANK.AA = "Hyper Puller" = 50
RANK.A = "High Puller" = 20
RANK.B = "Middle Puller" = 10
RANK.C = "First Pull" = 1

Total Repository
RANK.SSS = "God Repo Creator" = 100
RANK.SS = "Deep Repo Creator" = 90
RANK.S = "Super Repo Creator" = 80
RANK.AAA = "Ultra Repo Creator" = 50
RANK.AA = "Hyper Repo Creator" = 30
RANK.A = "High Repo Creator" = 20
RANK.B = "Middle Repo Creator" = 10
RANK.C = "First Repository" = 1

Languages
RANK.SECRET = "Rainbow Lang User" = 10

All Super Rank (All S rank)
RANK.SECRET = "S Rank Hacker" = 1

Joined 2020
RANK.SECRET = "Everything started..." = 1

Ancient Account (Joined before 2010)
RANK.SECRET = "Ancient User" = 1

Long Time Account
RANK.SECRET = "Village Elder" = 10

Multiple Organizations
RANK.SECRET = "Jack of all Trades" = 3

**Comment by Xisurthros** [comment]
I was curious as well. Searching through /src/trophy.ts I found this information.
I don't see why you wouldn't be able to change these values when replicating it locally.

Total Commits
RANK.SSS = "God Committer" = 4000
RANK.SS = "Deep Committer" = 2000
RANK.S = "Super Committer" = 1000
RANK.AAA = "Ultra Committer" = 500
RANK.AA = "Hyper Committer" = 200
RANK.A = "High Committer" = 100
RANK.B = "Middle Committer" = 10
RANK.C = "First Commit" = 1

Total Stars
RANK.SSS = "Super Stargazer" = 2000
RANK.SS = "High Stargazer" = 700
RANK.S = "Stargazer" = 200
RANK.AAA = "Super Star" = 100
RANK.AA = "High Star" = 50
RANK.A = "You are a Star" = 30
RANK.B = "Middle Star" = 10
RANK.C = "First Star" = 1

Total Followers
RANK.SSS = "Super Celebrity" = 1000
RANK.SS = "Ultra Celebrity" = 400
RANK.S = "Hyper Celebrity" = 200
RANK.AAA = "Famous User" = 100
RANK.AA = "Active User" = 50
RANK.A = "Dynamic User" = 20
RANK.B = "Many Friends" = 10
RANK.C = "First Friend" = 1

Total Issues
RANK.SSS = "God Issuer" = 1000
RANK.SS = "Deep Issuer" = 500
RANK.S = "Super Issuer" = 200
RANK.AAA = "Ultra Issuer" = 100
RANK.AA = "Hyper Issuer" = 50
RANK.A = "High Issuer" = 20
RANK.B = "Middle Issuer" = 10
RANK.C = "First Issue" = 1

Total Pull Requests
RANK.SSS = "God Puller" = 1000
RANK.SS = "Deep Puller" = 500
RANK.S = "Super Puller" = 200
RANK.AAA = "Ultra Puller" = 100
RANK.AA = "Hyper Puller" = 50
RANK.A = "High Puller" = 20
RANK.B = "Middle Puller" = 10
RANK.C = "First Pull" = 1

Total Repository
RANK.SSS = "God Repo Creator" = 100
RANK.SS = "Deep Repo Creator" = 90
RANK.S = "Super Repo Creator" = 80
RANK.AAA = "Ultra Repo Creator" = 50
RANK.AA = "Hyper Repo Creator" = 30
RANK.A = "High Repo Creator" = 20
RANK.B = "Middle Repo Creator" = 10
RANK.C = "First Repository" = 1

Languages
RANK.SECRET = "Rainbow Lang User" = 10

All Super Rank (All S rank)
RANK.SECRET = "S Rank Hacker" = 1

Joined 2020
RANK.SECRET = "Everything started..." = 1

Ancient Account (Joined before 2010)
RANK.SECRET = "Ancient User" = 1

Long Time Account
RANK.SECRET = "Village Elder" = 10

Multiple Organizations
RANK.SECRET = "Jack of all Trades" = 3
