### ISSUE TITLE
@torvalds profile crashes

### ISSUE THREAD

**Issue by 3kh0** [ryo-ma/github-profile-trophy#151]
https://github-profile-trophy.vercel.app/?username=torvalds

if you try to get the profile of @torvalds it does not work

![image](https://user-images.githubusercontent.com/58097612/188907608-ee4036ef-12c6-40b2-b1cd-15cc95032285.png)

**Comment by spenserblack** [comment]
Right now it doesn't seem unique to torvalds. https://github-profile-trophy.vercel.app/?username=3kh0 also seems to return a 500 response.

**Comment by 3kh0** [comment]
@spenserblack but it does work for me

![image](https://user-images.githubusercontent.com/58097612/188924317-2da535ba-0c14-44e4-8f0f-fa1ed5539550.png)

**Comment by 3kh0** [comment]
Oh now it works, seems like a temp issue

![image](https://user-images.githubusercontent.com/58097612/188924508-fb90404b-e075-4003-800b-b5cd9c6561c1.png)

**Comment by spenserblack** [comment]
Probably related: https://github.com/ryo-ma/github-profile-trophy/issues/150 and https://github.com/ryo-ma/github-profile-trophy/issues/141

As mentioned in https://github.com/ryo-ma/github-profile-trophy/issues/145 it could be the rate limit

@ryo-ma 「５００　ERROR」のIssue をピン止めするほうがいいですか？

**Comment by ryo-ma** [comment]
@spenserblack I have pinned #145.

I will do something about it soon.
