### ISSUE TITLE
How about "A+" rank?

### ISSUE THREAD

**Issue by kaili-yang** [ryo-ma/github-profile-trophy#153]
My rank is "A+" and I tried to set it as "A" or "AA", but both of them don't work.

**Comment by 3kh0** [comment]
Can you explain more about what you mean?

**Comment by ryo-ma** [comment]
It may not be the GitHubProfile Trophy.

**Comment by kaili-yang** [comment]
> 

There is no trophy for rank A+.

**Comment by kaili-yang** [comment]
> There is no trophy for rank A+. 
@3kh0

**Comment by MitkoVtori** [comment]
I think you're talking about the profile rank, not trophy. the profile ranks begin from A or A+ and the next Rank is A++
I am not sure if there's A+++ or Directly goes to S.
