### ISSUE TITLE
[QUERY] - Wanted to know About the latency the widget has? 

### ISSUE THREAD

**Issue by ChintzRuparel** [ryo-ma/github-profile-trophy#157]
Hey @ryo-ma 

Great work on the repository, Just wanted to enquire about the latency or the time it takes to fresh the widget?
Also is there a way to reduce it or make it as null latency based as possible 

Do lemme know 

Regards and Thanks, 
@ChintzRuparel

**Comment by 3kh0** [comment]
For me the latency is just about a minute. I do have to clear my cache by doing ctrl+shift+r. I do not know if this helps at all.

**Comment by ChintzRuparel** [comment]
Hey @3kh0 

For me the latency was about 15 mins. I did try clearing my cache but apparently that doesn't work.

Regards, 
Chintz Ruparel
