### ISSUE TITLE
Any way to use this as self hosted?

### ISSUE THREAD

**Issue by Nirzak** [ryo-ma/github-profile-trophy#158]
Hi, I was trying to deploy it on my own vercel instance to use it with my own github token. But It's giving me 500 Internal server error. I had set the API token as "GITHUB_API" on the environment variable section. Am I doing it wrong?

**Comment by Nirzak** [comment]
@ryo-ma

**Comment by ryo-ma** [comment]
GITHUB_TOKEN1 or GITHUB_TOKEN2

https://github.com/ryo-ma/github-profile-trophy/blob/7b8a6a4100893bbf1c721e563c6d07e04c79e479/src/github_api_client.ts#L113

**Comment by Nirzak** [comment]
Ok let me try. Thanks a lot for the reply!

**Comment by Nirzak** [comment]
> GITHUB_TOKEN1 and GITHUB_TOKEN2
> 
> https://github.com/ryo-ma/github-profile-trophy/blob/7b8a6a4100893bbf1c721e563c6d07e04c79e479/src/github_api_client.ts#L113

Thanks a lot. setting both the GITHUB_TOKEN1 and GITHUB_TOKEN2 works! I am closing the issue now.

**Comment by i-muniz** [comment]
@ryo-ma @Nirzak Hi folks. Sorry if this question is too noobie, but why is there two Github tokens? The code is not clear about that.
Shouldn't just one token be enough? 
I have set only one token, and it works fine.

**Comment by alexcastrodev** [comment]
> [@ryo-ma](https://github.com/ryo-ma) [@Nirzak](https://github.com/Nirzak) Hi folks. Sorry if this question is too noobie, but why is there two Github tokens? The code is not clear about that. Shouldn't just one token be enough? I have set only one token, and it works fine.

1 token is enough.
We use it to load balance. We receive millions of requests, and it raises [rate limit](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api). That's why 419 happen sometimes. :)

**Comment by 0x5b62656e5d** [comment]
@ryo-ma Attempting to selfhost this on vercel myself. Added `GITHUB_TOKEN1` and `GITHUB_TOKEN2` and verified that they are valid by making a test GraphQL request myself. I set `ENABLE_REDIS` to `false`. However, when I test my deployment, it keeps returning 504 invocation timeout.
