### ISSUE TITLE
[Feature] Align trophies 

### ISSUE THREAD

**Issue by YashasviChaurasia** [ryo-ma/github-profile-trophy#161]
A simple parameter that would allow trophies to be symmetrically centered or allow margins and padding between each other.
Currently, I am unable to align trophies to the center of my readme, and I am also not able to allow for gaps between two trophies.

It would be a great feature to put in maybe.
Thank you

**Comment by ryo-ma** [comment]
https://github.com/ryo-ma/github-profile-trophy#margin-width

**Comment by Arkapravo-Ghosh** [comment]
> A simple parameter that would allow trophies to be symmetrically centered or allow margins and padding between each other. Currently, I am unable to align trophies to the center of my readme, and I am also not able to allow for gaps between two trophies.
> 
> It would be a great feature to put in maybe. Thank you

Do it this way:
```html
<h3 align="center">GitHub Trophies</h3>
<div align="center">

![trophy](https://github-profile-trophy.vercel.app/?username=Arkapravo-Ghosh&theme=dark_lover&no-frame=true&no-bg=true&margin-w=4&column=5&title=MultiLanguage,Joined2020,Commits,Followers,Stars)
![trophy](https://github-profile-trophy.vercel.app/?username=Arkapravo-Ghosh&theme=dark_lover&no-frame=true&no-bg=true&margin-w=4&column=3&title=PullRequest,Repositories,Issues)
</div>
```
<h3 align="center">GitHub Trophies</h3>
<div align="center">

![trophy](https://github-profile-trophy.vercel.app/?username=Arkapravo-Ghosh&theme=dark_lover&no-frame=true&no-bg=true&margin-w=4&column=5&title=MultiLanguage,Joined2020,Commits,Followers,Stars)
![trophy](https://github-profile-trophy.vercel.app/?username=Arkapravo-Ghosh&theme=dark_lover&no-frame=true&no-bg=true&margin-w=4&column=3&title=PullRequest,Repositories,Issues)
</div>
