### ISSUE TITLE
[QUERY] - The Rainbow Lang User tag can be aligned with the other trophy tags 

### ISSUE THREAD

**Issue by ChintzRuparel** [ryo-ma/github-profile-trophy#163]
Hello @ryo-ma, 

The Rainbow lang user tag can be aligned with other trophy tags. If all come inline, It will be way easy to view. 
I have checked the whole repository to check if editing this is possible or no. 
If I am missing something please lemme know. 

Image Output for My Profile Stats 
<img width="894" alt="Screenshot 2022-10-27 at 19 37 28" src="https://user-images.githubusercontent.com/51440734/198308661-526285b9-296a-4b7c-b1c0-9ae70eb1881c.png">

Thanks and Regards,
@ChintzRuparel

**Comment by ryo-ma** [comment]
https://github.com/ryo-ma/ryo-ma

**Comment by ChintzRuparel** [comment]
Hey @ryo-ma 

It's Solved🚀
Thanks a ton! 

![image](https://user-images.githubusercontent.com/51440734/198501933-4c21c142-4ae5-4924-b508-1710a428e321.jpeg)

Thanks and Regards, 
@ChintzRuparel
