### ISSUE TITLE
How can I create & add my own trophy, without changing anything to the main code?

### ISSUE THREAD

**Issue by MitkoVtori** [ryo-ma/github-profile-trophy#171]

**Comment by FleetAdmiralJakob** [comment]
Would be nice to know... Maybe by forking this repository?

**Comment by MitkoVtori** [comment]
> Would be nice to know... Maybe by forking this repository?

I have though of that, but my intelegence is not enough to make my own link or at least make the trophy

**Comment by FleetAdmiralJakob** [comment]
Fork this repository and then deploy it on Vercel. There are many tutorials out there. But a guide from @ryo-ma would also be really nice

**Comment by MitkoVtori** [comment]
> Fork this repository and then deploy it on Vercel. There are many tutorials out there. But a guide from @ryo-ma would also be really nice

I may try
