### ISSUE TITLE
How many languages I need for the multilang trophy?

### ISSUE THREAD

**Issue by MitkoVtori** [ryo-ma/github-profile-trophy#172]

**Comment by CPScript** [comment]
mabey 6...

its a high number

**Comment by MitkoVtori** [comment]
> 12 i think

Well, I have 11 so maybe after one more language, I would recieve it :)

**Comment by MitkoVtori** [comment]
> mabey 6...
> 
> its a high number

nah, noway. 14 languages is garanteed, but we'll see how much it needs :)
