### ISSUE TITLE
Update trophy information quicker

### ISSUE THREAD

**Issue by SmashedFrenzy16** [ryo-ma/github-profile-trophy#175]
I have noticed tht it takes a while for trophy information to update. Can you please implement a way to make the updating process quicker?

**Comment by 3kh0** [comment]
I dont think this would be possible due to GitHub API limits

**Comment by hasain19** [comment]
why it doesn't work ?

**Comment by hasain19** [comment]
try to fixed it

**Comment by AlexcastroDev** [comment]
> I have noticed tht it takes a while for trophy information to update. Can you please implement a way to make the updating process quicker?

The current implementation is updating about 30 minutes, i will increase to some hours.

I dont know if is relevant decrease the time of revalidation.

I will close, since this have more than 8 months without updates.
