### ISSUE TITLE
Commits Trophy Glitch

### ISSUE THREAD

**Issue by SmashedFrenzy16** [ryo-ma/github-profile-trophy#179]
I have noticed that my commit trophy has glitched and is not matching my GitHub contributions graph. For example, on the contributions graph I have >1.1K commits but on the trophy it is merely 1.0K.

**Comment by KatarzynaChmielecka** [comment]
I have the same problem now :(

**Comment by bhavberi** [comment]
The number of contributions shown in the contributor's graph on the profile page consists of Commits + Issues + PRs + Code Reviews in the last year. Thus, it would not match the commits points in the trophies.
(It is not matching for me too, as far as I can see)

**Comment by AlexcastroDev** [comment]
if you have more question, re-open the issue
