### ISSUE TITLE
Trophies not showing on one line

### ISSUE THREAD

**Issue by MitkoVtori** [ryo-ma/github-profile-trophy#182]
### Hi, before two days I recieved one of the private trophies. The problem is, since this happened, the trophies are showing on two lines. Whatever size they are! Even when I make them really small, they still are on two lines. How can I make them on one line?

![Screenshot 2023-01-11 213212](https://user-images.githubusercontent.com/112943652/212460174-7e3e044a-9e3e-4097-8351-1a36ec1b37a4.png)

**Comment by RohiniKhandare98** [comment]
hey i have solution for your problem

**Comment by mosamaasif** [comment]
Hey. So what you can do is use "column" param (https://github.com/ryo-ma/github-profile-trophy#specify-the-maximum-row--column-size) to define number of trophies to show in a line. If you set column=-1 it will auto adapt, or you can set column=7 (in your case) to show them in one line. Check link for more details.

**Comment by MitkoVtori** [comment]
> Hey. So what you can do is use "column" param (https://github.com/ryo-ma/github-profile-trophy#specify-the-maximum-row--column-size) to define number of trophies to show in a line. If you set column=-1 it will auto adapt, or you can set column=7 (in your case) to show them in one line. Check link for more details.

Thank you!
