### ISSUE TITLE
Margin-w=4 causes error image not showing up.

### ISSUE THREAD

**Issue by mpotane** [ryo-ma/github-profile-trophy#184]
To replicate: add &margin-w=4 in the params.

**Comment by mohanyadav** [comment]
This works for me. Could you check if the error still exists?
`https://github-profile-trophy.vercel.app/?username=mohanyadav&margin-w=4`

![image](https://user-images.githubusercontent.com/11350400/214765046-459cf3ee-4562-4734-b4cd-834496bfc99b.png)

**Comment by mpotane** [comment]
> This works for me. Could you check if the error still exists? `https://github-profile-trophy.vercel.app/?username=mohanyadav&margin-w=4`
> 
> ![image](https://user-images.githubusercontent.com/11350400/214765046-459cf3ee-4562-4734-b4cd-834496bfc99b.png)

Yep it's working now. 🥳
