### ISSUE TITLE
Error on line 126 at column 56: AttValue: ' expected Below is a rendering of the page up to the first error.

### ISSUE THREAD

**Issue by bnbong** [ryo-ma/github-profile-trophy#187]
Hello,
I'm using Github-profile-trophy at my README profile well without problem, but today I found my readme profile trophy not properly marked.
When I went into the hyperlink of my trophy I wrote on readme, an error page was rendered.

The message is below:
This page contains the following errors:
error on line 126 at column 56: AttValue: ' expected
Below is a rendering of the page up to the first error.

Attached the more detailed page photo of this:
<img width="1507" alt="스크린샷 2023-01-31 오후 7 57 17" src="https://user-images.githubusercontent.com/55042923/215741794-3226b944-b475-4880-933e-b321c6899d97.png">

Here is my profile README.md link:
https://github.com/bnbong/bnbong/blob/main/README.md

Please let me know if there is any way I can solve this problem myself, otherwise I would appreciate it if you could solve this issue quickly.

Thank you for your useful service.

**Comment by ryo-ma** [comment]
It appears to be working correctly now.
I can't reproduce it.

**Comment by bnbong** [comment]
Oh, I checked. Thank you for your answer.
