### ISSUE TITLE
Secret Trophies

### ISSUE THREAD

**Issue by DURGESH716** [ryo-ma/github-profile-trophy#189]

**Comment by DURGESH716** [comment]
Can anyone list all the hidden trophies, two of them I have already unlocked

**Comment by hitenkoku** [comment]
https://github.com/ryo-ma/github-profile-trophy/blob/5378858628ea199bf583f08e85987ee80897ece8/src/trophy.ts#L106-L218

**Comment by AlexanderLivanov** [comment]
What is the trophy "MultiLanguage" awarded for?

**Comment by bhavberi** [comment]
> What is the trophy "MultiLanguage" awarded for?

I think it is for how many unique coding languages you have used until now in your repositories, and if it is greater than 10, then you get that secret trophy.
