### ISSUE TITLE
Change from ranks to achievements

### ISSUE THREAD

**Issue by jasper-zanjani** [ryo-ma/github-profile-trophy#2]
I just discovered your project, and I think it's fantastic! I immediately applied it to my own profile, and I couldn't be happier!

But I did want to point out that if you allow users to determine their own rank, then naturally they will want to assign themselves a higher rank to make themselves look better. This will hurt your project's credibility, because there is nothing stopping someone from being deceptive. I believe you may have been inspired by the letter grade produced by the [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) project?

However, if you adapt this idea to make achievement-style badges that cannot simply be faked by users, then I believe your project will have a very prosperous future. There will no longer be a need to serve precisely 6 trophies, you can serve as many achievements as the user's profile has earned according to your system.

I thank you for your effort, and I have starred and watched your repo.

**Comment by ryo-ma** [comment]
Thank you for the issue! Definitely, there are problems that you said.
I want users who feel low rank to use the rank as a learning goal. And, I thought that the problems are resolved by adding various SECRET Trophy.
In the future, I will add secret trophies that evaluate by various axes.
