### ISSUE TITLE
This Serverless Function has crashed. 

### ISSUE THREAD

**Issue by xamidi** [ryo-ma/github-profile-trophy#206]
I am currently getting the following [response](https://github-profile-trophy.vercel.app/?username=xamidi&theme=radical&column=3&margin%2Dw=9&margin%2Dh=9&title=MultiLanguage,LongTimeUser,Commits):

![grafik](https://github.com/ryo-ma/github-profile-trophy/assets/3799257/ccc68209-7893-4990-9d2c-8b54735e8aba)

Edit: Now it seems to be working again. How frequently does this occur, and if it does, is it always automatically fixed after at most a few minutes?

**Comment by AlexcastroDev** [comment]
> I am currently getting the following [response](https://github-profile-trophy.vercel.app/?username=xamidi&theme=radical&column=3&margin%2Dw=9&margin%2Dh=9&title=MultiLanguage,LongTimeUser,Commits):
> 
> ![grafik](https://user-images.githubusercontent.com/3799257/243393379-ccc68209-7893-4990-9d2c-8b54735e8aba.png)
> 
> Edit: Now it seems to be working again. How frequently does this occur, and if it does, is it always automatically fixed after at most a few minutes?

Thanks for your issue.

we improve the code and scale the server.
