### ISSUE TITLE
Including private repos

### ISSUE THREAD

**Issue by rasooltaghipoor** [ryo-ma/github-profile-trophy#207]
## What
Hi. Thanks for this great tool. 
I know this subject (Taking into account private repo stats) is introduced in #19 and the author has closed the issue as completed. But, it seems that the tool still does not consider private repos. Am I right? Or I've missed some settings?

Thanks.

**Comment by AlexcastroDev** [comment]
> ## What
> Hi. Thanks for this great tool. I know this subject (Taking into account private repo stats) is introduced in #19 and the author has closed the issue as completed. But, it seems that the tool still does not consider private repos. Am I right? Or I've missed some settings?
> 
> Thanks.

I can be wrong, but to have a visibility’s data of private, our GitHub token should have access to this repository, innit?
