### ISSUE TITLE
The Server Error 404

### ISSUE THREAD

**Issue by Retroz-W8** [ryo-ma/github-profile-trophy#208]
The database cannot recognize me. Its showing no user found.

**Comment by bhavberi** [comment]
![image](https://github.com/ryo-ma/github-profile-trophy/assets/43399374/8f785a2d-bc20-4071-ae60-c770f08213b7)

I think your stats are available on the link https://github-profile-trophy.vercel.app/?username=Retroz-W8 
(Photo attached for reference)
