### ISSUE TITLE
Can add trophy for Code review 

### ISSUE THREAD

**Issue by dsnehasish74** [ryo-ma/github-profile-trophy#21]

**Comment by arwazkhan189** [comment]
use this code
<img align="center" src="https://github-profile-trophy.vercel.app/?username=arwazkhan189&theme=dracula" alt="github trophy"/>

replace your username ... 👍

**Comment by Nirzak** [comment]
Yeah definitely it will be great for code reviewers!

**Comment by RayhanADev** [comment]
@Nirzak out of curiosity what is a code review and how do you do one (I think I do it already, just not sure)

**Comment by Nirzak** [comment]
> @Nirzak out of curiosity what is a code review and how do you do one (I think I do it already, just not sure)

In Github, Code review is when you review the pull requests of other GitHub projects. Simply reviewing the codes or approve them. Github also counts them as a contribution.

**Comment by RayhanADev** [comment]
Ah understood, thanks :)
