### ISSUE TITLE
Commits counter got stucked

### ISSUE THREAD

**Issue by JohnyP36** [ryo-ma/github-profile-trophy#212]
Since a couple of days my commit trophy lowered and stays at 1.1kpt. However I have 4.2k commits. 
See this screenshot or check at https://metrics.lecoq.io/about/JohnyP36: 
![afbeelding](https://github.com/ryo-ma/github-profile-trophy/assets/81161435/1b650be3-1a11-4cf8-a59e-537e5d1b85be).  

What happened?

**Comment by AlexcastroDev** [comment]
> Since a couple of days my commit trophy lowered and stays at 1.1kpt. However I have 4.2k commits. See this screenshot or check at https://metrics.lecoq.io/about/JohnyP36: ![afbeelding](https://user-images.githubusercontent.com/81161435/255897987-1b650be3-1a11-4cf8-a59e-537e5d1b85be.png).
> 
> What happened?

I dont think that Commits and Score stands for the same thing.

@ryo-ma right ?

**Comment by JohnyP36** [comment]
@AlexcastroDev Although you closed it.

> I don't think that Commits and Score stands for the same thing.

In the past is was equal, but if the calculating changed. I'm oke.
