### ISSUE TITLE
Deployment has been disabled 

### ISSUE THREAD

**Issue by Madhav-MKNC** [ryo-ma/github-profile-trophy#219]
![Screenshot_2023-09-25-16-02-11-927_com android chrome](https://github.com/ryo-ma/github-profile-trophy/assets/78339236/ef7fb72f-e9a8-4783-bcc1-b96d81910796)

**Comment by ivan-developer-01** [comment]
Duplicate of https://github.com/ryo-ma/github-profile-trophy/issues/217.

**Comment by Madhav-MKNC** [comment]
Didn't see that
