### ISSUE TITLE
Organization support

### ISSUE THREAD

**Issue by Potato1682** [ryo-ma/github-profile-trophy#23]
Please support repository of a user and the repository of the organization to which the user joins.
I think it is mainly suitable for users who are working within the organization.

**Comment by RayhanADev** [comment]
@Potato1682 Out of curiosity how would you handle the following situations:
> A user is in an organization with multiple repositories, only one of which the user contributed to.

or
> A user is in multiple organizations, only a few of which the user is actual active in.

Since this would give the user an unfair advantage in getting trophies. I have an idea I could implement, just getting this out of my head too :).

**Comment by D3vil0p3r** [comment]
You can manage it by roles in the organization, for example giving stars to the trophy only to the owner.

**Comment by D3vil0p3r** [comment]
Still relevant
