### ISSUE TITLE
Add labels to issues

### ISSUE THREAD

**Issue by CodeMaster7000** [ryo-ma/github-profile-trophy#239]
Add the 'Hacktoberfest' and 'good first issue' labels to issues to make it easier for beginners to contribute.

**Comment by ravindu9802** [comment]
Hey, @CodeMaster7000 , I want to work on this. Can you assign this to me?

**Comment by CodeMaster7000** [comment]
I do not have the permission to do so - only @ryo-ma can.

**Comment by ryo-ma** [comment]
already done?

**Comment by AlexcastroDev** [comment]
> Add the 'Hacktoberfest' and 'good first issue' labels to issues to make it easier for beginners to contribute.

we already have it

**Comment by CodeMaster7000** [comment]
Np!
