### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by codewithdeepak01** [ryo-ma/github-profile-trophy#24]
There is some bug

**Comment by ryo-ma** [comment]
l want to know the detail of the concrete bug.

**Comment by arwazkhan189** [comment]
use this code
`<img align="center" src="https://github-profile-trophy.vercel.app/?username=arwazkhan189&theme=dracula" alt="github trophy"/>`

replace your username 👍

**Comment by codewithdeepak01** [comment]
I will try it👍👍
