### ISSUE TITLE
Vercel-Deployment Link is expired.

### ISSUE THREAD

**Issue by VirendrKumarYadav** [ryo-ma/github-profile-trophy#241]
Your GitHub profile Vercel deployment Link not working : 
[https://github-profile-trophy.vercel.app/ ]()
![image](https://github.com/ryo-ma/github-profile-trophy/assets/87600216/9f151c8f-5841-4bcc-aba4-f2913db8ccda)

**Comment by AlexcastroDev** [comment]
> Your GitHub profile Vercel deployment Link not working : https://github-profile-trophy.vercel.app/ ![image](https://user-images.githubusercontent.com/87600216/275793605-9f151c8f-5841-4bcc-aba4-f2913db8ccda.png)

Read the message, lol

https://github-profile-trophy.vercel.app/?username=VirendrKumarYadav
