### ISSUE TITLE
There is a Space, at the end of the Image of the Trophies

### ISSUE THREAD

**Issue by Jonak-Adipta-Kalita** [ryo-ma/github-profile-trophy#242]
![Screenshot 2023-10-18 191856](https://github.com/ryo-ma/github-profile-trophy/assets/70377522/616f37a2-469f-41ec-9ae7-561c59dba032)

If you don't see the space in the above picture, change your theme! You'll see it

**Comment by AlexcastroDev** [comment]
> ![Screenshot 2023-10-18 191856](https://user-images.githubusercontent.com/70377522/276273552-616f37a2-469f-41ec-9ae7-561c59dba032.png)
> 
> If you don't see the space in the above picture, change your theme! You'll see it

I can see a space beween them, so what you mean ?

**Comment by Jonak-Adipta-Kalita** [comment]
> > ![Screenshot 2023-10-18 191856](https://user-images.githubusercontent.com/70377522/276273552-616f37a2-469f-41ec-9ae7-561c59dba032.png)
> > If you don't see the space in the above picture, change your theme! You'll see it
> 
> I can see a space beween them, so what you mean ?

![image](https://github.com/ryo-ma/github-profile-trophy/assets/70377522/e5d140f5-5899-4798-aa92-2df522f86f94)

I meant after the very last picture (lemme know if you see the issue now from the picture I just sent)

**Comment by AlexcastroDev** [comment]
> see the issue now from the picture I

Oh, i see now.

Thanks for reporting

**Comment by Jonak-Adipta-Kalita** [comment]
> > see the issue now from the picture I
> 
> Oh, i see now.
> 
> Thanks for reporting

My Pleasure 😄

**Comment by Jonak-Adipta-Kalita** [comment]
I will see I can try to solve the Issue :)

**Comment by Jonak-Adipta-Kalita** [comment]
It got turned to Stale?
