### ISSUE TITLE
Vercel and GitHub PAT permissions

### ISSUE THREAD

**Issue by lasersPew** [ryo-ma/github-profile-trophy#245]
Heya! Tried to selfhost it using [Vercel](https://github-profile-trophy-laserspew.vercel.app/) and it can't seem to work even if I create a PAT(both fine-grained and classic one) with repo and user permissions. Here are the error logs:
```
headers: {
Accept: "application/json, text/plain, */*",
"Content-Type": "application/json;charset=utf-8",
Authorization: "bearer "
},
baseURL: "https://api.github.com/graphql",
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
withCredentials: false,
adapter: [Function: fetchAdapter],
responseType: "json",
xsrfCookieName: "XSRF-TOKEN",
xsrfHeaderName: "X-XSRF-TOKEN",
maxContentLength: -1,
validateStatus: [Function (anonymous)],
maxRedirects: 5,
socketPath: null,
responseEncoding: "utf8"
},
request: undefined,
response: {
data: {
message: "Bad credentials",
documentation_url: "https://docs.github.com/graphql"
},
status: 401,
statusText: "Unauthorized",
headers: {
"access-control-allow-origin": "*",
"access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLim"... 183 more characters,
"content-length": "83",
"content-security-policy": "default-src 'none'",
"content-type": "application/json; charset=utf-8",
date: "Tue, 31 Oct 2023 16:16:50 GMT",
"referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
server: "GitHub.com",
"strict-transport-security": "max-age=31536000; includeSubdomains; preload",
vary: "Accept-Encoding, Accept, X-Requested-With",
"x-content-type-options": "nosniff",
"x-frame-options": "deny",
"x-github-media-type": "github.v4",
"x-github-request-id": "C724:30DA:9DD3BE8:14373388:65412871",
"x-ratelimit-limit": "0",
"x-ratelimit-remaining": "0",
"x-ratelimit-reset": "1698772610",
"x-ratelimit-resource": "graphql",
"x-ratelimit-used": "0",
"x-xss-protection": "0"
},
config: {
url: "",
method: "post",
data: '{"query":"\\n  query userInfo($username: String!) {\\n    user(login: $username) {\\n      repositories'... 402 more characters,
headers: {
Accept: "application/json, text/plain, */*",
"Content-Type": "application/json;charset=utf-8",
Authorization: "bearer "
},
baseURL: "https://api.github.com/graphql",
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
withCredentials: false,
adapter: [Function: fetchAdapter],
responseType: "json",
xsrfCookieName: "XSRF-TOKEN",
xsrfHeaderName: "X-XSRF-TOKEN",
maxContentLength: -1,
validateStatus: [Function (anonymous)],
maxRedirects: 5,
socketPath: null,
responseEncoding: "utf8"
}
},
isSoxaError: true,
toJSON: [Function (anonymous)]
}
Error: Max retries (2) exceeded.
at Retry.fetch (file:///vercel/path0/src/Helpers/Retry.ts:58:11)
at eventLoopTick (ext:core/01_core.js:197:13)
at async GithubApiService.executeQuery (file:///vercel/path0/src/Services/GithubApiService.ts:101:24)
at async GithubApiService.requestUserRepository (file:///vercel/path0/src/Services/GithubApiService.ts:32:12)
at async GithubApiService.requestUserInfo (file:///vercel/path0/src/Services/GithubApiService.ts:60:24)
at async app (file:///vercel/path0/api/index.ts:85:30)
at async staticRenderRegeneration (file:///vercel/path0/src/StaticRenderRegeneration/index.ts:29:20)
at async processEvents (file:///vercel/path0/.vercel/builders/node_modules/vercel-deno/dist/runtime.ts:104:16)
ServiceError: not found
at GithubApiService.executeQuery (file:///vercel/path0/src/Services/GithubApiService.ts:120:14)
at eventLoopTick (ext:core/01_core.js:197:13)
at async GithubApiService.requestUserRepository (file:///vercel/path0/src/Services/GithubApiService.ts:32:12)
at async GithubApiService.requestUserInfo (file:///vercel/path0/src/Services/GithubApiService.ts:60:24)
at async app (file:///vercel/path0/api/index.ts:85:30)
at async staticRenderRegeneration (file:///vercel/path0/src/StaticRenderRegeneration/index.ts:29:20)
at async processEvents (file:///vercel/path0/.vercel/builders/node_modules/vercel-deno/dist/runtime.ts:104:16)
Caused by NOT_FOUND {
name: "ServiceError",
cause: "NOT_FOUND"
}

```

**Comment by AlexcastroDev** [comment]
> Heya! Tried to selfhost it using [Vercel](https://github-profile-trophy-laserspew.vercel.app/) and it can't seem to work even if I create a PAT(both fine-grained and classic one) with repo and user permissions. Here are the error logs:
> 
> ```
> headers: {
> Accept: "application/json, text/plain, */*",
> "Content-Type": "application/json;charset=utf-8",
> Authorization: "bearer "
> },
> baseURL: "https://api.github.com/graphql",
> transformRequest: [ [Function: transformRequest] ],
> transformResponse: [ [Function: transformResponse] ],
> timeout: 0,
> withCredentials: false,
> adapter: [Function: fetchAdapter],
> responseType: "json",
> xsrfCookieName: "XSRF-TOKEN",
> xsrfHeaderName: "X-XSRF-TOKEN",
> maxContentLength: -1,
> validateStatus: [Function (anonymous)],
> maxRedirects: 5,
> socketPath: null,
> responseEncoding: "utf8"
> },
> request: undefined,
> response: {
> data: {
> message: "Bad credentials",
> documentation_url: "https://docs.github.com/graphql"
> },
> status: 401,
> statusText: "Unauthorized",
> headers: {
> "access-control-allow-origin": "*",
> "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLim"... 183 more characters,
> "content-length": "83",
> "content-security-policy": "default-src 'none'",
> "content-type": "application/json; charset=utf-8",
> date: "Tue, 31 Oct 2023 16:16:50 GMT",
> "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
> server: "GitHub.com",
> "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
> vary: "Accept-Encoding, Accept, X-Requested-With",
> "x-content-type-options": "nosniff",
> "x-frame-options": "deny",
> "x-github-media-type": "github.v4",
> "x-github-request-id": "C724:30DA:9DD3BE8:14373388:65412871",
> "x-ratelimit-limit": "0",
> "x-ratelimit-remaining": "0",
> "x-ratelimit-reset": "1698772610",
> "x-ratelimit-resource": "graphql",
> "x-ratelimit-used": "0",
> "x-xss-protection": "0"
> },
> config: {
> url: "",
> method: "post",
> data: '{"query":"\\n  query userInfo($username: String!) {\\n    user(login: $username) {\\n      repositories'... 402 more characters,
> headers: {
> Accept: "application/json, text/plain, */*",
> "Content-Type": "application/json;charset=utf-8",
> Authorization: "bearer "
> },
> baseURL: "https://api.github.com/graphql",
> transformRequest: [ [Function: transformRequest] ],
> transformResponse: [ [Function: transformResponse] ],
> timeout: 0,
> withCredentials: false,
> adapter: [Function: fetchAdapter],
> responseType: "json",
> xsrfCookieName: "XSRF-TOKEN",
> xsrfHeaderName: "X-XSRF-TOKEN",
> maxContentLength: -1,
> validateStatus: [Function (anonymous)],
> maxRedirects: 5,
> socketPath: null,
> responseEncoding: "utf8"
> }
> },
> isSoxaError: true,
> toJSON: [Function (anonymous)]
> }
> Error: Max retries (2) exceeded.
> at Retry.fetch (file:///vercel/path0/src/Helpers/Retry.ts:58:11)
> at eventLoopTick (ext:core/01_core.js:197:13)
> at async GithubApiService.executeQuery (file:///vercel/path0/src/Services/GithubApiService.ts:101:24)
> at async GithubApiService.requestUserRepository (file:///vercel/path0/src/Services/GithubApiService.ts:32:12)
> at async GithubApiService.requestUserInfo (file:///vercel/path0/src/Services/GithubApiService.ts:60:24)
> at async app (file:///vercel/path0/api/index.ts:85:30)
> at async staticRenderRegeneration (file:///vercel/path0/src/StaticRenderRegeneration/index.ts:29:20)
> at async processEvents (file:///vercel/path0/.vercel/builders/node_modules/vercel-deno/dist/runtime.ts:104:16)
> ServiceError: not found
> at GithubApiService.executeQuery (file:///vercel/path0/src/Services/GithubApiService.ts:120:14)
> at eventLoopTick (ext:core/01_core.js:197:13)
> at async GithubApiService.requestUserRepository (file:///vercel/path0/src/Services/GithubApiService.ts:32:12)
> at async GithubApiService.requestUserInfo (file:///vercel/path0/src/Services/GithubApiService.ts:60:24)
> at async app (file:///vercel/path0/api/index.ts:85:30)
> at async staticRenderRegeneration (file:///vercel/path0/src/StaticRenderRegeneration/index.ts:29:20)
> at async processEvents (file:///vercel/path0/.vercel/builders/node_modules/vercel-deno/dist/runtime.ts:104:16)
> Caused by NOT_FOUND {
> name: "ServiceError",
> cause: "NOT_FOUND"
> }
> ```

did you create the .env file with Gtihub token?

**Comment by AlexcastroDev** [comment]
dont forget that you should add GITHUB_TOKEN on vercel env settings

**Comment by AlexcastroDev** [comment]
> > did you create the .env file with Gtihub token?
> > Nope...
> 
> > dont forget that you should add GITHUB_TOKEN on vercel env settings
> > Bru it even come to a point that GITHUB_TOKEN1 use classic while GITHUB_TOKEN2 use fine-grained

try do a debugger in you application and check if .envs is really reaching in the application.
