### ISSUE TITLE
[Question] GitHub API How to

### ISSUE THREAD

**Issue by george-gca** [ryo-ma/github-profile-trophy#246]
Hi, I was thinking about trying to implement a few new trophies, but I currently don't understand how to do it. I know that, for a starter, I will have to create or modify some queries in [index.ts](https://github.com/ryo-ma/github-profile-trophy/blob/master/src/Schemas/index.ts), but I couldn't find any information about the structure of these queries. They don't look like the ones given in the [official documentation](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28). Are they from an old version? If so, where can I find the documentation for it?

**Comment by ryo-ma** [comment]
We using GraphQL
https://docs.github.com/en/graphql
