### ISSUE TITLE
How to add for private repos

### ISSUE THREAD

**Issue by thisha-me** [ryo-ma/github-profile-trophy#247]

**Comment by vietvh-3042** [comment]
Same, Except for commits, it seems that things related to PR and Issue are not calculated with private repos

**Comment by AlexcastroDev** [comment]
> Same, Except for commits, it seems that things related to PR and Issue are not calculated with private repos

It’s the limitation of GitHub api, innit? We can’t change this 😂

**Comment by igorskyflyer** [comment]
> > Same, Except for commits, it seems that things related to PR and Issue are not calculated with private repos
> 
> It’s the limitation of GitHub api, innit? We can’t change this 😂

One could do so, if the repo was deployed on their own instance of Vercel and by providing an access token with the private repo/stats permission...

**Comment by AlexcastroDev** [comment]
> > > Same, Except for commits, it seems that things related to PR and Issue are not calculated with private repos
> > 
> > 
> > It’s the limitation of GitHub api, innit? We can’t change this 😂
> 
> One could do so, if the repo was deployed on their own instance of Vercel and by providing an access token with the private repo/stats permission...

You can fork and deploy yourself. dont you ?
