### ISSUE TITLE
Feature Request: Customisable Trophy Size and Spacing

### ISSUE THREAD

**Issue by yihong1120** [ryo-ma/github-profile-trophy#254]
### Description

Hello there,

I've been using the GitHub Profile Trophy on my profile, and it's a fantastic way to showcase achievements in a visually appealing manner. I appreciate the work that has gone into creating this project.

### Suggestion

However, I've noticed that while we can control the margin width and height between trophies, we currently don't have the option to adjust the size of the trophies themselves or the spacing directly around each individual trophy. I believe adding this feature would provide an even greater level of customisation for users who may want to fit the trophies into a specific layout on their profiles.

### Implementation

Ideally, it would be great to have additional query parameters such as `trophy-size` and `trophy-spacing` that allow for fine-tuning of the trophy display. This could help with creating a more tailored look and feel for the trophies on different types of GitHub profile READMEs.

### Conclusion

Thank you for considering this feature request. I'm looking forward to any updates on this, and I'm more than willing to contribute to the discussion if needed.

Best regards,
yihong1120

**Comment by goyalyashpal** [comment]
yeah, the card size (height) for each individual trophy is way toooo small to be comfortably readable.
