### ISSUE TITLE
[Enhancement] Transparent/native theme.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ryo-ma/github-profile-trophy#257]
As https://github.com/anuraghazra/github-readme-stats/issues/3613#issue-2100699842 and https://github.com/anuraghazra/github-readme-stats/issues/3614#issue-2100703035 demonstrate, being able to adhere to GitHub's theme like https://github.com/anuraghazra/github-readme-stats/blob/2259870e8e6e31864e3ac46159998a14d070a4ca/readme.md#use-the-transparent-theme allows would be incredibly useful for me.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ryo-ma/github-profile-trophy/issues/257#event-11959645374

@GitHub-Actions, which is a uselessly arbitrary definition. See? It's no longer stale. What was the point of that?

**Comment by AlexcastroDev** [comment]
> As [anuraghazra/github-readme-stats#3613 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/3613#issue-2100699842) and [anuraghazra/github-readme-stats#3614 (comment)](https://github.com/anuraghazra/github-readme-stats/issues/3614#issue-2100703035) demonstrate, being able to adhere to GitHub's theme like https://github.com/anuraghazra/github-readme-stats/blob/2259870e8e6e31864e3ac46159998a14d070a4ca/readme.md#use-the-transparent-theme allows would be incredibly useful for me.

Hi, 

At the moment, my priority in this project is to fix some things and implement more unit tests.

Both Ryo-ma and I dedicate a small part of our time to improve this project. If you want, feel free to address this topic yourself.

If I have some free time, I'll look into it, in case nobody else takes it

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ryo-ma/github-profile-trophy/issues/257#issuecomment-2089406445

@GitHub-Actions

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ryo-ma/github-profile-trophy/issues/257#issuecomment-2143668551

@GitHub-Actions, https://github.com/ryo-ma/github-profile-trophy/issues/257#issuecomment-1971208136.

**Comment by a2ys** [comment]
An issue similar to this is #25. PR #28 fixes this issue, you can check if it works for you!

Also, in the README, [this](https://github.com/ryo-ma/github-profile-trophy?tab=readme-ov-file#transparent-background) section addresses your concern as well!

Check and confirm!
