### ISSUE TITLE
PR Trophy Issue

### ISSUE THREAD

**Issue by Vijay-2003** [ryo-ma/github-profile-trophy#263]
I just made a pull request and its not showing up in trophy

**Comment by AlexcastroDev** [comment]
> I just made a pull request and its not showing up in trophy

Can you link here?

**Comment by Iqtidartara** [comment]
Just Copy the Edit able code and paste in your commit file and change the logins .

**Comment by Vijay-2003** [comment]
> > I just made a pull request and its not showing up in trophy
> 
> Can you link here?

https://github-profile-trophy.vercel.app/?username=Vijay-2003

**Comment by AlexcastroDev** [comment]
> > > I just made a pull request and its not showing up in trophy
> > 
> > 
> > Can you link here?
> 
> https://github-profile-trophy.vercel.app/?username=Vijay-2003

I mean the PR u open

**Comment by Vijay-2003** [comment]
> > > > I just made a pull request and its not showing up in trophy
> > > 
> > > 
> > > Can you link here?
> > 
> > 
> > https://github-profile-trophy.vercel.app/?username=Vijay-2003
> 
> I mean the PR u open

https://github.com/pulls?q=is%3Apr+author%3AVijay-2003+archived%3Afalse+is%3Aclosed

**Comment by AlexcastroDev** [comment]
> > > > > I just made a pull request and its not showing up in trophy
> > > > 
> > > > 
> > > > Can you link here?
> > > 
> > > 
> > > https://github-profile-trophy.vercel.app/?username=Vijay-2003
> > 
> > 
> > I mean the PR u open
> 
> https://github.com/pulls?q=is%3Apr+author%3AVijay-2003+archived%3Afalse+is%3Aclosed

It’s not our project 🤔
