### ISSUE TITLE
Filter by title exclude

### ISSUE THREAD

**Issue by d9k** [ryo-ma/github-profile-trophy#265]
It is possible to filter ranks:

> You can also exclude ranks.
> 
> ```
> https://github-profile-trophy.vercel.app/?username=ryo-ma&rank=-C,-B
> ```

Please add ability to filter by excluding multiple titles too! For example:

https://github-profile-trophy.vercel.app/?username=ryo-ma&title=-Reviews,-Experience

(now server sends empty image with zero height in response)

**Comment by a2ys** [comment]
Hey @d9k,

Although the GitHub Actions bot closed this issue marking it as stale, I raised a PR (PR #276) which addresses this same issue, I didn't see this issue previously.

You can subscribe to the PR to get notified when the PR is merged. I'll mention this issue in the PR.
