### ISSUE TITLE
Transparent theme

### ISSUE THREAD

**Issue by 39palakved** [ryo-ma/github-profile-trophy#267]

**Comment by a2ys** [comment]
can you give at least some brief description of what you want?

**Comment by a2ys** [comment]
@adalfarus 

Check #257.

**Comment by adalfarus** [comment]
> @adalfarus
> 
> Check #257 and tell if your concern is addressed.

Yes, thanks a lot :)

**Comment by a2ys** [comment]
@adalfarus 

Yeah, no worries! Close this issue if you're done!

**Comment by adalfarus** [comment]
I didn't open it
