### ISSUE TITLE
Could not center trophies

### ISSUE THREAD

**Issue by Jay-Karia** [ryo-ma/github-profile-trophy#278]
After filtering trophies, I could not center the trophies as it occupies same width previously without filter.

![trophies issue](https://github.com/user-attachments/assets/37eacf06-ee9b-4fcb-ae52-149c08d482f0)

Adding a parameter like `&center=true` would be better.

**Comment by eduardblbulyan** [comment]
You should specify your trophies seperately and add parameter `column=-1` to avoid extra space.Like this `

```
<p align="center">
  <a href="https://github.com/eduardblbulyan">
    <img src="https://github-profile-trophy.vercel.app/?username=USERNAME&theme=SOME_THEME&column=-1&title=Repositories,Commits" alt="USERNAME" />
  </a>
</p>
```

**Comment by eduardblbulyan** [comment]
You can check it in my page too

**Comment by Jay-Karia** [comment]
Yeah, your solution works.
It would be better to add a new parameter `center` to center trophies.
