### ISSUE TITLE
Theme not rendering

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [ryo-ma/github-profile-trophy#287]
When i add a theme to the themes file and then re run the program it seems to not show up and i dont know why:
stats:
uname: `Linux leon 6.10.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 24 Jul 2024 22:25:43 +0000 x86_64 GNU/Linux`
node: `v20.13.1`
deno:
```
deno 1.45.4 (release, x86_64-unknown-linux-gnu)
v8 12.7.224.13
typescript 5.5.2
```

**Comment by Jay-Karia** [comment]
Can you please show the theme file.

**Comment by NeonGamerBot-QK** [comment]
https://github.com/NeonGamerBot-QK/github-profile-trophy/blob/d4260fc0fd44a16057e8358eb3222f5bee6f507e/src/theme.ts

**Comment by Jay-Karia** [comment]
Updated file with the new theme.


> https://github.com/NeonGamerBot-QK/github-profile-trophy/blob/d4260fc0fd44a16057e8358eb3222f5bee6f507e/src/theme.ts

This one is original file.

**Comment by Jay-Karia** [comment]
If you have added a new theme.
Restart the deno application, as hot reload is not supported.
