### ISSUE TITLE
Incorrect width size

### ISSUE THREAD

**Issue by Ehsan-Habibagahi** [ryo-ma/github-profile-trophy#289]
Well,... when the titles of the achievements are limit to specific ones the total width of the image is not decreased.
Example:

https://github-profile-trophy.vercel.app/?username=ehsan-habibagahi&theme=juicyfresh&title=Experience,Commits,Followers,PullRequest,Stars,Repositories

The width is still `800` while `600` might be right. This problem presents itself when trying to center the image

**Comment by AleksandarHaralanov** [comment]
Any chance this can be looked into again. Would love if there was a fix to it.
