### ISSUE TITLE
rank=S but not show S

### ISSUE THREAD

**Issue by Hart-Li** [ryo-ma/github-profile-trophy#290]
you can diff img:
1.<img src="https://github-profile-trophy.vercel.app/?username=hart-li&rank=SSS,SS,S,AAA,A" alt="hart-li" />
img_src:https://github-profile-trophy.vercel.app/?username=hart-li&rank=SSS,SS,S,AAA,A
2.<img src="https://github-profile-trophy.vercel.app/?username=hart-li" alt="hart-li" />
img_src:https://github-profile-trophy.vercel.app/?username=hart-li
question:title=MultiLanguage  is S，but not show

**Comment by ryo-ma** [comment]
MultiLanguage is SECRET rank
https://github.com/ryo-ma/github-profile-trophy?tab=readme-ov-file#about-rank
