### ISSUE TITLE
Is it down?

### ISSUE THREAD

**Issue by DefinetlyNotAI** [ryo-ma/github-profile-trophy#298]
It suddenly stopped working for me for 4 days, also i randomly lost a secret trophy for no reason

**Comment by alexcastrodev** [comment]
Maybe something on Vercel. It all depends on the Github API and calculation.

I'm not sure how it exacly works, but it remember me to start add more tests for Trophies :P

**Comment by DefinetlyNotAI** [comment]
> Maybe something on Vercel. It all depends on the Github API and calculation.
> 
> I'm not sure how it exacly works, but it remember me to start add more tests for Trophies :P

Ok, thanks

**Comment by DefinetlyNotAI** [comment]
Its working now, but the secret trophy doesnt lol...
