### ISSUE TITLE
What does experience mean?

### ISSUE THREAD

**Issue by DmitriyKolesnikM8O** [ryo-ma/github-profile-trophy#308]
And what should I do to increase it?
![image](https://github.com/user-attachments/assets/5016015d-9f92-43a3-aad1-05ae68353fdf)

**Comment by KingHowler** [comment]
Account Age

**Comment by gustavokennedy** [comment]
Hi @DmitriyKolesnikM8O

This topic has already been [discussed here](https://github.com/ryo-ma/github-profile-trophy/issues/258).

But it is based on the age of your account.
