### ISSUE TITLE
About Experience trophy

### ISSUE THREAD

**Issue by karthikyadav-git** [ryo-ma/github-profile-trophy#311]
On what basis does the experience point increase?

**Comment by jaydeep-khandla** [comment]
The points increases according to how long you’ve been on GitHub, beginning from your join date and this logic is implemented in the code.

I found the relevant implementation in the code-base under `/src/trophy.ts`, specifically within the `AccountDurationTrophy` class.

**Comment by sahillihas** [comment]
The experience points increase based on the duration of the user's account on GitHub. The longer the account has been active, the higher the rank and points.

https://github.com/ryo-ma/github-profile-trophy/blob/bc4e735c815315ca7abed8c9d79e4bd638daab22/src/trophy.ts#L270-L319

Closes #311

**Comment by sahillihas** [comment]
The experience points increase based on the duration of the user's account on GitHub. The longer the account has been active, the higher the rank and points.

https://github.com/ryo-ma/github-profile-trophy/blob/bc4e735c815315ca7abed8c9d79e4bd638daab22/src/trophy.ts#L270-L319

close #311
