### ISSUE TITLE
Multilanguage giving wrong result

### ISSUE THREAD

**Issue by JayantGoel001** [ryo-ma/github-profile-trophy#32]
Multilanguage of GitHub trophy is giving wrong results I have 16 unique languages public repos but it showing only 14 kindly help.
Thank You.

**Comment by ryo-ma** [comment]
I think the problem is that I only get the first 100 repositories.
If you increase the number of repositories to be acquired, the response will be slow...

**Comment by JayantGoel001** [comment]
@ryo-ma Can it somehow increase and get correct count?
Any Solution Possible.?
