### ISSUE TITLE
FEAT: Theme param?

### ISSUE THREAD

**Issue by spenserblack** [ryo-ma/github-profile-trophy#4]
I think it would be neat if this project supported an optional `theme` param.
For example `?theme=gruvbox` could change rank bar from `#0366d6` to `#fabd2f`.

What do you think?

**Comment by ryo-ma** [comment]
I think that I want to support the feature. 
But,  I am short of hands for developing now.
I want to consider it as a roadmap.

**Comment by spenserblack** [comment]
>I think that I want to support the feature.

Awesome!

>But, I am short of hands for developing now.

In that case, can I be assigned to this issue?

**Comment by ryo-ma** [comment]
I'm really glad! I assign you to this issue!
