### ISSUE TITLE
Add Documentation for Buddhism and Oldie Themes

### ISSUE THREAD

**Issue by RayhanADev** [ryo-ma/github-profile-trophy#40]
Just the two new themes that I've noticed that are still undocumented.
I'd do it myself but it seem's you have a documentation convention I don't want to mess up ;P.

**Comment by ryo-ma** [comment]
OK. I'm busy on a business trip right now, so I'll write it later.

**Comment by RayhanADev** [comment]
Kewl

**Comment by ryo-ma** [comment]
Done
