### ISSUE TITLE
Add a trophy type for the contributed to section

### ISSUE THREAD

**Issue by Nirzak** [ryo-ma/github-profile-trophy#43]
How about adding a trophy type for the number of repositories that someone contributed to. It's also there on the Github Readme Card in the last row. So, Definitely, it can be fetched from API. Also, there's another trophy type can be added for number of code reviews.

**Comment by RayhanADev** [comment]
Kewl idea, I wonder if they will implement it!

Also I believe the second part was mentioned in #21

**Comment by Nirzak** [comment]
> Kewl idea, I wonder if they will implement it!
> 
> Also I believe the second part was mentioned in #21

Yeah. There's another feature request for code review count feature
