### ISSUE TITLE
Count more languages in Repositories

### ISSUE THREAD

**Issue by RayhanADev** [ryo-ma/github-profile-trophy#47]
Heya!

So there is **no reasonable way to get the Multiple Language User** trophy unless you make repositories purely coded in one language. Instead of querying for the first most used language in a repository could you possibly check for **the top 3 most used languages in a repository?** That way languages that don't really get used a lot in bytecode can also be factored into consideration.

Thanks!

> Also, congrats on 1000 stars! 🎉

**Comment by ryo-ma** [comment]
I got it. Is there any reason why the number is 3? I thought it was okay to raise it to about 10.

**Comment by RayhanADev** [comment]
No reason at all, I just didn't want to raise it *way* to high you know. The problem with 10 however is someone can create a single repository with 10 different languages and they can get the trophy. If you raise the repository language count to 10 then you should also raise the requirement a bit higher, or you could go with a lower amount (5?) and that should work to balance things out.

**Comment by ryo-ma** [comment]
OK. For the time being, I will adopt 3.
