### ISSUE TITLE
Add gaps?

### ISSUE THREAD

**Issue by eai04191** [ryo-ma/github-profile-trophy#5]
This project is great, but the trophies sticking to the other stuff doesn't seem to look very nice. I think adding a (changeable) gap would make it better!

**Comment by ryo-ma** [comment]
Thank you for the issue!
I can't imagine a little. For example, how would you do that?

**Comment by ryo-ma** [comment]
OK. I got it.
I think it's a good idea, so I want to add it to the option parameter!
I'd like to include it in the roadmap for now.

**Comment by qoomon** [comment]
any progress on this?

**Comment by ryo-ma** [comment]
I didn't think it was stamped so much.
I will release it within a week.

**Comment by ryo-ma** [comment]
@eai04191 @qoomon 

I have released the margin option parameters.

Please confirm the following document.

https://github.com/ryo-ma/github-profile-trophy/blob/master/README.md#margin-width

<img width="365" src="https://user-images.githubusercontent.com/6661165/93668949-46b82600-facb-11ea-9c4e-6263eff05a30.png">

**Comment by qoomon** [comment]
Looks so much better now, thanks a lot.

**Comment by eai04191** [comment]
Thanks! New one looks good!
