### ISSUE TITLE
[Idea] Merging statistics with GitLab

### ISSUE THREAD

**Issue by PandaFoss** [ryo-ma/github-profile-trophy#50]
I know the project currently takes stats from GitHub, but sometimes some developers use both GitHub and GitLab (or Bitbucket, etc.) Is there a possibility to optionally merge the stats with GitLab?
Since the readme tries to show the time spent on development, I think it would be nice to show the totality and not just one platform. (Although I also understand that, if accepted, it is an improvement that does not happen overnight :stuck_out_tongue: ).
Thank you! :smile:

**Comment by RayhanADev** [comment]
Sound's interesting! Let's see what @.ryo-ma says.

**Comment by RayhanADev** [comment]
If we do this, I can certainly adding in API implementation.

**Comment by ryo-ma** [comment]
Is GitLab having an API?

**Comment by RayhanADev** [comment]
Yep! https://docs.gitlab.com/ee/api/
