### ISSUE TITLE
[Feature Request] Option for Centered Last Row

### ISSUE THREAD

**Issue by Penguinlay** [ryo-ma/github-profile-trophy#56]
It is helpful when the image is rendered within `p` that is aligned center.
For compatibility, this can be set to be false by default.

Example use case is here: https://github.com/Penguinlay/Penguinlay

**Comment by ryo-ma** [comment]
It's okay to have that function, but currently, you can use the following methods.
https://github.com/ryo-ma/github-profile-trophy#specify-the-maximum-row--column-size

Welcome if you send this project a pull request

**Comment by Penguinlay** [comment]
I will take a look. I think it's better to implement alignment (left, right or center) rather than center alignment as boolean.

**Comment by Penguinlay** [comment]
I am not that familiar with Vercel project and I'm quite occupied these days. So, if anyone wants to take on this project, feel free to do so.
