### ISSUE TITLE
[Feature Request] Please add discord-old-blurple.

### ISSUE THREAD

**Issue by AlphaNecron** [ryo-ma/github-profile-trophy#58]
Here's the theme: https://github.com/anuraghazra/github-readme-stats/commit/2b0efb8d299e614d1baf17c8a41a645146c5249b

**Comment by RayhanADev** [comment]
Do you think you can add this theme in? You change the values in [this file](https://github.com/ryo-ma/github-profile-trophy/blob/master/src/theme.ts), so if you think you can handle it go ahead and possibly create a fork!

**Comment by AlphaNecron** [comment]
Hmm okay.
