### ISSUE TITLE
Bug: Owning organizations does not count towards the organizations secret trophy.

### ISSUE THREAD

**Issue by Time-dragon** [ryo-ma/github-profile-trophy#62]

**Comment by RayhanADev** [comment]
Are you sure? I own an organization (and am in two other organizations) and still have the trophy.

**Comment by Time-dragon** [comment]
> Are you sure? I own an organization (and am in two other organizations) and still have the trophy.

I own all my organizations.

**Comment by RayhanADev** [comment]
> > Are you sure? I own an organization (and am in two other organizations) and still have the trophy.
> 
> I own all my organizations.

May be because of that 🤷. Lemme check the code.

**Comment by Time-dragon** [comment]
Pinging @ryo-ma for help.

**Comment by spenserblack** [comment]
It looks like at least 2 organizations are required. I only see 1 organization when viewing your account.
Do you have any private organizations? I don't believe they would be counted, since I doubt that the token that is used would have access to data about *another user's* private organizations.

**Comment by Time-dragon** [comment]
> It looks like at least 3 organizations are required. I only see 1 organization when viewing your account.
> Do you have any private organizations? I don't believe they would be counted, since I doubt that the token that is used would have access to data about _another user's_ private organizations.

![image](https://user-images.githubusercontent.com/82837930/123317489-1428d700-d4fc-11eb-9fab-bdfeaf546652.png)

**Comment by spenserblack** [comment]
What do you see when you view your profile when logged out?
![screenshot](https://user-images.githubusercontent.com/8546709/123319592-987c5980-d4fe-11eb-8ee4-8ba5c795d9a1.png)

**Comment by Time-dragon** [comment]
> What do you see when you view your profile when logged out?
> Screenshot of what I see.
> ![screenshot](https://user-images.githubusercontent.com/8546709/123319592-987c5980-d4fe-11eb-8ee4-8ba5c795d9a1.png)

I see that too!

**Comment by RayhanADev** [comment]
@Time-dragon that's probably why, the organizations need to be public. Try making two of your orgs public (if you can).

**Comment by Time-dragon** [comment]
@RayhanADev I need help.

**Comment by ryo-ma** [comment]
@Time-dragon  The reason has already been written, it's a private organization. It's not a bug.

**Comment by spenserblack** [comment]
>I need help.

Help to make the organizations public? https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership

**Comment by Time-dragon** [comment]
@spenserblack Did that but now it hates me

**Comment by RayhanADev** [comment]
@Time-dragon I see you have the trophy now 🎉?

**Comment by Time-dragon** [comment]
> @Time-dragon I see you have the trophy now 🎉?

Woohoo!
