### ISSUE TITLE
Improve Requirements for Organization Secret Trophy

### ISSUE THREAD

**Issue by rayhanadev** [ryo-ma/github-profile-trophy#63]
After finding out that the new secret trophy requires the person to be in _[REDACTED]_ organizations, the first reaction would be to make _[REDACTED]_ organizations to get it. Unsurprisingly this works, however it doesn't seem right. Instead there should be checking and requirements on the organizations before awarding the trophy:

Proposals:
1. The organization must be (at least) a week old
2. The organization must contain more than one account
3. The organization must contain one or more repositories
4. ~~The person should be in at least one organization that was not created by them~~* **

\* I believe this one might be controversial. Any thoughts?
** Dropped this

**Comment by ryo-ma** [comment]
I got your feelings. Regarding `2.` and `3.`, I think it a good idea to add to the rules. I think `1.` has little effect on the problem. I couldn't understand the meaning of `4.` well.

Alternatively, there may be a way to add value by applying rule `2.` to create a new trophy.
ex. Big Org Owner: The organization must contain than ten accounts and, must be the owner of its organization.

**Comment by RayhanADev** [comment]
@ryo-ma gotcha, if you want I can open a PR adding in `2.` and `3.` to the current trophy.

> I couldn't understand the meaning of `4.` well.

So if a user is in three public organizations and they created (i.e. they are the owner of) two organizations then the third one must be an outside organization they are a member of in order to get the trophy. It kinda makes sure they didn't just create three organizations and add fake accounts to it. More credibility.

> Alternatively, there may be a way to add value by applying rule `2.` to create a new trophy.
> ex. Big Org Owner: The organization must contain than ten accounts and, must be the owner of its organization.

I think there are a fair bit *too* many secret trophies 😅. Maybe we can make this one a ranked trophy starting at an organization with 2 accounts and working up through the ranks?

**Comment by spenserblack** [comment]
I understand the reasons for `1.` and `4.`, but here are my thoughts on it:

### `1.`

This just means the user has to wait a week to get the trophy.

***

### `4.`

> It kinda makes sure they didn't just create three organizations and add fake accounts to it.

If I have real account A and fake account B, then creating 2 organizations with A and 1 with B would pass this requirement, wouldn't it?

I also think that `4.` would be biased against some very important contributors. The meaning of creating an organization and joining an organization are different. To create an organization is to be a leader in a project IMO. To join an organization is to be a very important contributor, but not necessarily the leader/creator of something. Is it fair that someone who is always the leader wouldn't get the trophy?

**Comment by RayhanADev** [comment]
@spenserblack 
> This just means the user has to wait a week to get the trophy.

Fair enough, but more "secure" is better than not secure at all.

> I also think that `4.` would be biased against some very important contributors.

Yeah that's what I was running in the back of my mind and I do agree with you. I'll drop `4.` from the list then.

**Comment by ryo-ma** [comment]
@RayhanADev  I got it. If you make a pull request about `2.` and `3.`, I will accept it.

**Comment by Time-dragon** [comment]
More than one account is a bad idea.

**Comment by ryo-ma** [comment]
@Time-dragon Can you explain why it's a bad idea?

**Comment by Time-dragon** [comment]
@ryo-ma It's a bad idea because hosting an organization nobody else is in is a great way to store repositories when you get tired of making more on your account so you resort to organizations.

**Comment by ryo-ma** [comment]
> you get tired of making more on your account so you resort to organizations.
I don't understand the situation. 

It is officially stated that the GitHub Organization is aimed at collaboration.
https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations

**Comment by RayhanADev** [comment]
@ryo-ma yeah I’m currently moving to a different city right now so I’m on my phone, not my computer. I’ll have it setup tomorrow and I can continue what I was working on but if that’s too late feel free to go ahead and PR yourself.

Sorry about this, I tried to finish ASAP but the movers came much earlier than expected!

**Comment by ryo-ma** [comment]
@RayhanADev It's not particularly urgent, so it's okay at your own pace. Living in a different city is exciting!

**Comment by D3vil0p3r** [comment]
Currently is there a chance to add in "Star Trophy" also the stars coming from the org I am the owner? If so, how?

**Comment by D3vil0p3r** [comment]
Still relevant.
