### ISSUE TITLE
Themed trophies not updating

### ISSUE THREAD

**Issue by gabrielconlon** [ryo-ma/github-profile-trophy#66]
seems to be an issue with at least some themes not updating. 
see attached photo.

![Screen Shot 2021-08-16 at 2 34 16 PM](https://user-images.githubusercontent.com/3859926/129626174-5bb9bff9-e8d9-44fb-a279-5924e90f3829.png)

**Comment by ryo-ma** [comment]
I don't understand the problem. Can you explain a little more concretely?

**Comment by gabrielconlon** [comment]
This may honestly be on GitHub's end, but there seams to be an issue that certain themes are not updating or it is taking a very long time (hours to days).  For instance, up above I had the darker theme on my RREADME.md and noticed the total repositories and commit's numbers did not match my GitHub stats.  but with the default light theme, the numbers updated.

This was both embedded in the README.md and again in a separate browser window.  I am having the same issue with anuraghazra's readme-stats repository [GitHub-README-stats](https://github.com/anuraghazra/github-readme-stats) as well now, which leads me to wonder I this is just lag on GitHub's end.

Sorry for the confusion

**Comment by ryo-ma** [comment]
I think it's probably a cache issue.  When the theme changes, the URL changes, so the cache also changes.

Currently, the cache max-age is set to 2 hours.
https://github.com/ryo-ma/github-profile-trophy/blob/522489babee6f27368c4458924e49ee4f80aa5ae/index.ts#L81


About cache:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
