### ISSUE TITLE
Line wrap

### ISSUE THREAD

**Issue by antfu** [ryo-ma/github-profile-trophy#7]
Kinda happy to I get the hidden trophy 😝, however I hope they could be present in the same line instead of wrapping.

[![](https://github-profile-trophy.vercel.app/?username=antfu)](https://github-profile-trophy.vercel.app/?username=antfu)

**Comment by ryo-ma** [comment]
You should check this.

https://github.com/ryo-ma/github-profile-trophy#specify-the-maximum-row--column-size

# Demo

![sample](https://github-profile-trophy.vercel.app/?username=antfu&column=7)


```
[![trophy](https://github-profile-trophy.vercel.app/?username=antfu&column=7)](https://github.com/ryo-ma/github-profile-trophy)
```

**Comment by antfu** [comment]
Thanks!
