### ISSUE TITLE
Add Theme

### ISSUE THREAD

**Issue by MrBlueBird2** [ryo-ma/github-profile-trophy#70]
I created a new theme named gitdimmed, so, @ryo-ma , can you update README.md and, add my theme??
Theme Name: GitDimmed
Author: MrBlueBird2 (Badri Vishal)
Theme Example: https://github-profile-trophy.vercel.app/?username=MrBlueBird2&row=2&column=6&theme=gitdimmed&column=8&no-frame=false&no-bg=false%22

**Comment by ryo-ma** [comment]
Done.
