### ISSUE TITLE
Unknown title of Followers trophy

### ISSUE THREAD

**Issue by wizard-28** [ryo-ma/github-profile-trophy#71]
![img](https://0x0.st/-vvO.png)

It's showing `Unknown` even though I have 3 followers.

**Comment by spenserblack** [comment]
I looked at your portfolio and I don't think you set the right username for the image URL query parameter.
Shouldn't it be `?username=wizard-28`?

**Comment by wizard-28** [comment]
Yeah. Sorry for that. I fixed it now, but now the MultiLanguage trophy is gone. Can you tell me what are the requirements to unlock it?
