### ISSUE TITLE
website link is not working.

### ISSUE THREAD

**Issue by Abhijay007** [ryo-ma/github-profile-trophy#72]
website link in repo description is not working, is says "Can not find a query parameter: username"

**Comment by spenserblack** [comment]
`https://github-profile-trophy.vercel.app/?username=Abhijay007`
![Result](https://github-profile-trophy.vercel.app/?username=Abhijay007)

**Comment by 3kh0** [comment]
@spenserblack Close this since it is a Stale issue and it was solved?

**Comment by spenserblack** [comment]
@3kh0 I'm not a maintainer, you'll need to reach out to @ryo-ma for things like closing issues.
