### ISSUE TITLE
Include Private Repo PRs

### ISSUE THREAD

**Issue by MrBlueBird2** [ryo-ma/github-profile-trophy#76]
The commit trophy counts the commits of public + private repos, but, the pull request trophy counts only public pull requests, can anybody fix this??

**Comment by Akhi2007** [comment]
_com_ple__ted____

**Comment by MrBlueBird2** [comment]
> _com_ple__ted____

Let me see

**Comment by MrBlueBird2** [comment]
> _com_ple__ted____

Still not fixed

**Comment by Emilien-Lambert** [comment]
Still no solutions?

**Comment by MrBlueBird2** [comment]
Nope

**Comment by Nixxen** [comment]
It might be possible to do something similar to what [github readme stats](https://github.com/anuraghazra/github-readme-stats) has done and add a Github personal access token to the requests(see their readme for hosting your own Vercel instance). That way users could host their own instance of Github Profile Trophy with their own PAT, with access to their private repositories.

This would require a "modular" way to read the PAT within the code, I.e. from a .env.

**Comment by mbadr2200** [comment]
> It might be possible to do something similar to what [github readme stats](https://github.com/anuraghazra/github-readme-stats) has done and add a Github personal access token to the requests(see their readme for hosting your own Vercel instance). That way users could host their own instance of Github Profile Trophy with their own PAT, with access to their private repositories.
> 
> This would require a "modular" way to read the PAT within the code, I.e. from a .env.
> 
> Edit: Just tested it. There's already a "GITHUB_TOKEN" env variable in the code. Add your PAT to that when deploying to Vercel (or any other host). Works perfectly.

is it still working ? , I try it and I get this error 
```
{ message: [32m"Bad credentials"[39m, documentation_url: [32m"https://docs.github.com/graphql"[39m }
TypeError: Cannot read properties of undefined (reading 'data')
at GithubAPIClient.request (file:///var/task/src/github_api_client.ts:130:20)
at async GithubAPIClient.requestUserIssue (file:///var/task/src/github_api_client.ts:69:12)
at async Promise.all (index 1)
at async GithubAPIClient.requestUserInfo (file:///var/task/src/github_api_client.ts:20:21)
at async default (file:///var/task/index.ts:59:20)
at async processEvents (file:///var/task/.runtime.ts:190:16)
{ message: [32m"Bad credentials"[39m, documentation_url: [32m"https://docs.github.com/graphql"[39m }
{ message: [32m"Bad credentials"[39m, documentation_url: [32m"https://docs.github.com/graphql"[39m }
{ message: [32m"Bad credentials"[39m, documentation_url: [32m"https://docs.github.com/graphql"[39m }

```

**Comment by mbadr2200** [comment]
Changed the Env Variable to `GITHUB_TOKEN1` and now its working

**Comment by AdithyaGopakumar** [comment]
Is there any other way that this can be done?
