### ISSUE TITLE
followers count not getting updated 

### ISSUE THREAD

**Issue by GOWTHAM-EGANATHAN** [ryo-ma/github-profile-trophy#77]

**Comment by ryo-ma** [comment]
@GOWTHAM-EGANATHAN Please describe a more detailed issue

**Comment by GOWTHAM-EGANATHAN** [comment]
@ryo-ma Issue is when a follower instantly follows your is not immediately reflected in your profile.
It requires some time to get reflected in profile. 
closing the issue hence issue not reproducing.
