### ISSUE TITLE
2020 Trophy Text Cut-off Error

### ISSUE THREAD

**Issue by Lukas-Batema** [ryo-ma/github-profile-trophy#79]
The 2020 Secret Trophy is getting its text cut-off, as shown in the screenshot below. Also, what is the point of that trophy, why is it more important than other years?
![Screenshot 2021-09-29 5 52 46 AM](https://user-images.githubusercontent.com/55695493/135246445-488e4b7c-d1dd-4738-9043-311dd4e7b6ab.png)

**Comment by ryo-ma** [comment]
This is correct.
2020 is the year this product was released.

**Comment by Lukas-Batema** [comment]
> This is correct. 2020 is the year this product was released.

Ohhhhh... Okay, thanks for the help!
