### ISSUE TITLE
🏆Looking for the new themes

### ISSUE THREAD

**Issue by ryo-ma** [ryo-ma/github-profile-trophy#9]
There are still a few trophy color themes.🏆
Waiting for your contributions.

You can add a new theme to the following file.

https://github.com/ryo-ma/github-profile-trophy/blob/master/src/theme.ts

How to run.

https://github.com/ryo-ma/github-profile-trophy#contribution-guide

**Comment by ryo-ma** [comment]
#11 Dracula theme

**Comment by Pralhad-Nasane** [comment]
@ryo-ma please include tokyonight theme

**Comment by Aryankpoor** [comment]
Just for idea, how about a black and white theme?

**Comment by adityadees** [comment]
#29 juicy fresh

**Comment by RayhanADev** [comment]
#38 Black and White (Oldie) Theme
@Aryankpoor think that's what you were looking for?

**Comment by vivian-dai** [comment]
idea: [tokyonight](https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night)

**Comment by Time-dragon** [comment]
For "darkhub" make the trophies a dark color

**Comment by jos3s** [comment]
#60 Add OneStar

**Comment by QuentiumYT** [comment]
#67 Algolia theme

**Comment by MrBlueBird2** [comment]
What About Monokai Theme??

**Comment by Camroku** [comment]
#103 Apprentice theme

**Comment by trejess** [comment]
Onestar

**Comment by ez-sherlock** [comment]
I have another dope theme idea in mind. How can I contribute to this project?

**Comment by Azzylondon** [comment]
Splendid 👍

**Comment by N3v1** [comment]
Hi everyone,
maybe I have an idea for a theme - **Shades of purple** 
**[See this VSCode Theme](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple)**

**Comment by ymbtc757** [comment]
invite me

**Comment by sm202020** [comment]
The theme is gonna be amazing

**Comment by Y0i7** [comment]
What about Neon Theme??? Something like the SynthWave '84 - VS Code theme. :3

**Comment by isitreallyalive** [comment]
#334 catppuccin themes

**Comment by raushank95931-a11y** [comment]
ravi kumar
