### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by alabotski** [ryo-ma/github-profile-trophy#90]
Stopped working. Before everything was fine

`[![trophy](https://github-profile-trophy.vercel.app/?username=alabotski)](https://github.com/ryo-ma/github-profile-trophy)`

![image](https://user-images.githubusercontent.com/439337/138549335-d2437b16-7afc-4f81-9366-ac510b4cf4fd.png)

**Comment by Eurus-Holmes** [comment]
> This project is currently occurring server resource limit issues.

how to fix it?

**Comment by ryo-ma** [comment]
@alabotski @nyngwang @Eurus-Holmes @batazor
I have improved it. Please make sure your trophies.

**Comment by batazor** [comment]
seems to work

**Comment by nyngwang** [comment]
> @alabotski @nyngwang @Eurus-Holmes @batazor I have improved it. Please make sure your trophies.

It works now. Thank you!
