### ISSUE TITLE
Request to add a github action

### ISSUE THREAD

**Issue by Jassi10000-zz** [ryo-ma/github-profile-trophy#96]
I see that the repo is quite engaging 
I would love to see a github - action welcoming all the new contributors on their issues and Prs

If you love the idea , assign me

**Comment by 3kh0** [comment]
@ryo-ma Stale issue

**Comment by spenserblack** [comment]
@3kh0 Thanks for the clarification, this is what I get for only reading the issue title :laughing:

**Comment by 3kh0** [comment]
@spenserblack no problem!

**Comment by Jassi10000** [comment]
@spenserblack @3kh0 Guys , is this repo up for hacktoberfest2022 ?
If no , I think you can add labels so that people can contribute

**Comment by spenserblack** [comment]
@Jassi10000 
@3kh0 and I aren't maintainers, we just participate in discussions. You'll need to ask @ryo-ma.
